### ISSUE TITLE
Selection: CPC Impact Voting Members

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1143]
Each Impact project may nominate up to two members through a process of their choosing. Once nominated the member must be ratified by the CPC Voting members before becoming a Voting member.

For more information please see https://github.com/openjs-foundation/cross-project-council/blob/main/CPC-CHARTER.md#voting-members

### Nomination Process
Projects should comment in this issue with the project name and their nominees. Nomination window is two weeks:August 14th-August 25h

```[tasklist]
### Tasks
- [x] Nominations From Appium https://github.com/appium/appium/issues/19084
- [x] Nominations From Dojo
- [x] Nominations From Electron
- [x] Nominations From jQuery
- [x] Nominations From Node https://github.com/nodejs/admin/issues/819
- [x] Nominations From webpack https://github.com/webpack/webpack.js.org/issues/7006
- [x] CPC Ratify Nominations August 28 - September 1
- [x] Announce winners September 4
```

**Comment by bensternthal** [comment]
I am tagging in all current voting members from each impact project. 

As mentioned in the issue description, each Impact project may nominate up to two members through a process of their choosing. Once a decision is reached, please comment on this issue with the project name and your nominees. 

- Appium @imurchie @Jonahss 
- Dojo @dylans 
- Electron @erickzhao @bnb 
- jQuery @dmethvin @timmywil 
- Node.js: @Trott @joesepi 
- webpack: @TheLarkInn @sokra

**Comment by timmywil** [comment]
Nominations from jQuery: Michał Gołębiowski-Owczarek (@mgol) and myself (@timmywil)

Thanks to @dmethvin for serving thus far and welcome @mgol!

**Comment by erickzhao** [comment]
:electron: For Electron, we'll renominate @erickzhao and @bnb.

**Comment by dylans** [comment]
Nominations for Dojo: @dylans

**Comment by bensternthal** [comment]
Communicated via email, webpack nominated @TheLarkInn and @alexander-akait (https://github.com/alexander-akait)

**Comment by bensternthal** [comment]
Nominations for Appium @jlipps & @KazuCocoa

**Comment by joesepi** [comment]
@Trott and I will continue representing Node.js. Thanks!

Node.js Admin issue: https://github.com/nodejs/admin/issues/819

**Comment by bensternthal** [comment]
Per https://github.com/openjs-foundation/cross-project-council/pull/1161, closing this out.
