### ISSUE TITLE
Revamping the travel fund

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#1147]
As traveling is picking up again we're coming close to max out our travel fund this year.

Additionally, the fairly ad hoc processes we had in place aren't scaling up that well. They also have [privacy issues](https://github.com/openjs-foundation/cross-project-council/issues/397) that we are now committed to fix.

As a result we're going to revamp the travel fund with the following draft goals and requirements in mind (this is an opinionated summary of two different [working](https://github.com/openjs-foundation/cross-project-council/issues/397#issuecomment-1664719695) [sessions](https://docs.google.com/document/d/13Ocz4VMn-31CT8ZaqUZ0U_fLeMWJqRs2mwStmx_EChA/edit) on the topic):

1. **provide financial support for active independent contributors** to participate in events that benefit OpenJSF projects, working groups, or collab spaces.
2. **support diversity and inclusion**.
3. be publicly **transparent** about how those funds are used
    - be able to share anonymized data publicly, for example:
        - funds requested vs. fund accepted
        - how much funds are distributed by project/WG/collab space
        - how much  funds are distributed by event
        - how much funds are distributed to independent contributors vs. employed contributors
        - how much funds are distributed to contributors who self-report as member of an underrepresented minority
    - have a private papertrail of what decisions were made, by whom, and their rationale
4. be mindful of contributor's **privacy**
    - make decisions in private
    - do not share names or location of funded individuals without their agreement
    - agreement for information to be shared publicly cannot have impact on eligibility
5. be **responsive**
    - acknowledge receipt of request immediately
    - approve or reject requests quickly (ideally within 2 business days or at a given date if we manage requests in batches for specific events)
    - if fund is rejected, inform requester as to why, with escalation path (CPC meeting?)
    - if request needs escalation, inform requester right away plus explain why
6. be **efficient**
    - delegate process and most decision-making to foundation staff with the ability to escalate back to the CPC or project maintainers when necessary
    - have clear guidelines for how to approve requests
    - request relevant information from requesters to identify
        - which projects they're contributing to,
        - if they're doing so in a personal capacity or as part of their job
     - escalation path to maintainers to approve active contribution when in doubt
         - have a list of project maintainers
         - have clear guidelines for maintainers on how to assess eligibility
     - escalation path to CPC for any contentious issue
     - use a solution that CPC members and project maintainers can be onboarded to quickly
     
## Workstreams / Areas Of Improvement
- New user flow, from a contributor perspective how do they request travel funding? (Google form?)
- CPC approval flow, how does the CPC intake and ultimately approve funding requests? (list of main events we're expecting to support, request batching, announcing deadline by which requests have to be received, CPF-style)
- Budget tracking, reporting and yearly budget setting (potentially dividing up among groups)
- Transparency reports
- Clarify purpose of Fund (goal setting and related policy)

```[tasklist]
### Tasks
- [ ] https://github.com/openjs-foundation/cross-project-council/issues/1154
- [ ] https://github.com/openjs-foundation/cross-project-council/issues/1164
- [ ] https://github.com/openjs-foundation/cross-project-council/issues/1165
- [ ] https://github.com/openjs-foundation/cross-project-council/issues/1166
- [ ] https://github.com/openjs-foundation/cross-project-council/issues/1167
```

**Comment by PaulaPaul** [comment]
It would be helpful to outline the expectations of member organizations (at least for the Silver level and above) who have employees who are contributors and are attending collab summits or speaking, to determine their eligibility for travel funds (for example, would funds be capped at a certain amount and only available for speakers?).  Also, it would be helpful to have aa list of acceptable expenses that can be covered by travel funds (for example, only economy flights).

**Comment by bensternthal** [comment]
Folks, [here is a document with recommendations for changing the Travel Fund process](https://docs.google.com/document/d/10Tl09Bw2820rQjeYoAPiltA7YkUUetNTK-gBlPa-r-o/edit?usp=sharing). The opinions here are my own, and I look forward to iterating on this with you. 

Please feel free to comment directly in the doc. I can also open up edit permissions for specific folks.  Just ask.

**Comment by ovflowd** [comment]
Thanks for making that doc, @bensternthal! Super appreciate 🙇

**Comment by tobie** [comment]
# Working session summary

**Date:** 2023-08-29
**Present:** @bensternthal, @PaulaPaul, @ovflowd, @edsadr, @Ethan-Arrowood, @tobie, @ctcpip
_(LMK if I missed anyone and apologies if I did.)_

---

## 1. Presentation of Ben's proposal

@bensternthal offered a summary of his [proposal](https://docs.google.com/document/d/10Tl09Bw2820rQjeYoAPiltA7YkUUetNTK-gBlPa-r-o/edit?usp=sharing). It's trying to solve three problems:
1. The CPC has no visibility on the budget and so is operating in the dark
2. There no clear process to approve or reject requests. _(This hasn't been much of an issue so far since so few people had been traveling up until this year)_
3. The current process is privacy invasive to requesters _(and the CPC has agreed to fix this)_

He's offering a number of recommendations to solve these issues:

1. Have a fixed budget per event. _(It was pointed out that this worked for some events but not for all cases)_
2. Provide regular updates to the CPC about spend
3. Move the request intake to a google form to guarantee requester privacy.
4. Develop a scoring rubric for the CPC to help de-bias decision making, encode OpenJSF values, and provide transparency and predictability to requesters.

## 2. Group discussion

1. The group discussed whether they were in agreement with the overall proposal. General feeling was that the proposal was going in the right direction and should be adopted. There was a suggestion to focus exclusively on solving the privacy questions first, but that idea was abandoned when it was pointed out that current lack of process was also big concern, and that solving privacy issues would require to implement most other recommendations anyway.
2. The group then discussed the scoring rubric proposal in particular. This also met strong approbation. However, the group pointed out that the rubric should be used as a guideline, tuned, and regularly assessed by the CPC, and not be used as rigid and inflexible system.
3. There was a discussion about what criteria should be used to assess funding requests. The group agreed that this was a question that was difficult but that the rest of the work could move forward even if there was immediate consensus about this. Enough information should be collected from requesters to have flexibility going forward to tune the scoring rubric according to what the CPC believed the fund should support. Yearly reviews should be ran to assess whether the fund was having the desired impact and to modify the rubric's parameter accordingly.

## 3. Next steps

The group insisted that a speedy resolution was important and the next steps were agree upon.

1. A summary of this conversation would be brought to the CPC
2. The group recommends that the CPC adopts Ben's proposal (or a simplified version of Ben's proposal if there's an MVP in there)
3. Folks should start working on the scoring rubric in issue #1154, initially focusing on collecting necessary information rather than assigning weights.

**Comment by mcollina** [comment]
I would recommend we address the privacy issue first and then iterate.

**Comment by tobie** [comment]
I've been pushing for the privacy aspect for _years_ at this point, so I'm quite happy to see lots of support for it over the past couple of weeks. However, having looked at what would be needed to implement the privacy preserving aspects, I don't see how they don't also include about 80% of the rest of the process Ben is suggesting (i.e. something similar to the MVP I'm suggesting). @mcollina if either you or @Ethan-Arrowood have something specific in mind, and the cycles to then help implement it, would you mind outlining it in a concrete proposal? If not, I'm fairly concerned that this is just going to set us back instead of moving us forward.

**Comment by mcollina** [comment]
All of what @bensternthal has outlined from a process aspect does not need an aggreement on the "score" to be implemented. I propose we just go ahead with that.

**Comment by tobie** [comment]
I think we're in strong agreement, here; we can entirely work on the rubric in parallel of starting to implement @bensternthal's proposal.

And as mentioned in above, we can also separate the rubric into two parts and ship them separately:

1. agreeing on the information we want to gather (which is fairly straightforward and I have started to draft), and 
2. agreeing on how we weight the responses to those questions (this might be a little more contentious and risks taking longer).

Concretely that means that the CPC must approve moving forward with @bensternthal's proposal in our next meeting.

**Comment by mhdawson** [comment]
One thought I had while catching up on this issue, is that I think `Approvals would be made by whomever attends that meeting, and decisions captured in a document.` is good for approvals, but for rejections we likely want something like an email to CPC members so that nobody is later surprised by a rejection and there is some time for those not in attendance to advocate for approval instead of rejection before the rejectee is informed.

**Comment by mcollina** [comment]
I don't think we should make these  decisions synchronously.

**Comment by tobie** [comment]
CPC agrees with the overall direction. If you have issues with this direction please voice concerns early.

@benjamingr will start breaking up the work on GitHub and keep the CPC updated on progress regularly.

Working session on this planned for next week.

**Comment by bensternthal** [comment]
@tobie you tagged in the wrong Benjamin in that last comment :) I am @bensternthal

**Comment by tobie** [comment]
Fixed. Thanks!

**Comment by joesepi** [comment]
I added this comment to a different issue relating to the Travel fund, but I should have added it to this issue. Copying here for visibility

---

We had a very productive CPC working session today and made good progress on the travel fund. Below is a summary.
 
[Travel Form](https://forms.gle/qQCd3Rhq223e1Cc37)
We reviewed the questions on the form and feel this is good enough to proceed. We can always adjust later. You may notice the DEI section in the form is currently empty -- we plan to add that portion back in very soon. Just awaiting some guidance around data retention if I remember correctly.
 
[Process Recommendations](https://docs.google.com/document/d/10Tl09Bw2820rQjeYoAPiltA7YkUUetNTK-gBlPa-r-o/edit)
The working session participants [recommend](https://docs.google.com/document/d/10Tl09Bw2820rQjeYoAPiltA7YkUUetNTK-gBlPa-r-o/edit#heading=h.baxa9cw1owrt) we define budgets per quarter with flexibility around things like rollover and perhaps specific event budgets (like collab summits)
The working session participants [recommend](https://docs.google.com/document/d/10Tl09Bw2820rQjeYoAPiltA7YkUUetNTK-gBlPa-r-o/edit#heading=h.qyg11a7kvot7) we approve travel fund requests every two weeks, likely as a part of the CPC meetings.
The working session participants used the form questions to develop a [V1 scoring rubric](https://docs.google.com/document/d/10Tl09Bw2820rQjeYoAPiltA7YkUUetNTK-gBlPa-r-o/edit#heading=h.fbxtnhs2b9da). We think this is a good place to start and recommend using the next working session to dive into assigning points/scoring
 
All of this is malleable as we move forward but this progress is great and starts to set us up nicely for next year.

**Comment by bensternthal** [comment]
PR for new process is here https://github.com/openjs-foundation/cross-project-council/pull/1230

**Comment by PaulaPaul** [comment]
There was discussion at the CPC call about whether one grant per person year would be effective, or if there should be a monetary cap per year per person (e.g. a 2000 cap) that could be spread across multiple requests.  Looking at the requests from 2023, requests ranged from a little less than 1000 to over 3000, and a few individuals had multiple requests: https://github.com/openjs-foundation/community-fund/blob/main/programs/travel-fund/2023.md

**Comment by ljharb** [comment]
Our bottleneck so far has been $, not the number of people helped, so I’d hope we go with a cap that matches our bottleneck.
