### ISSUE TITLE
Simplifying election process

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#1148]
As discussed in https://github.com/openjs-foundation/cross-project-council/issues/1145#issuecomment-1677950051 the election process is overly complex and is unnecessarily different for each CPC role.

As @bensternthal is running the elections, he offered to propose some changes to simplify things after the current election cycle.

```[tasklist]
### Tasks
- [ ] https://github.com/openjs-foundation/cross-project-council/issues/1227
- [ ] Refactor CPC Roles
- [ ] Refactor CPC Election Process
```
