### ISSUE TITLE
Post-Bootstrap work to be managed by CPC

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#115]
**** CURRENTLY MANAGED IN PROJECT BOARDS ****

* BOOTSTRAP [closed] - https://github.com/openjs-foundation/bootstrap/projects/2
* POST-BOOTSTRAP - https://github.com/openjs-foundation/bootstrap/projects/3

HISTORICAL DATA

Issue to build list of checkboxed items we need to work on/progress

* Bootstrapping
  - [x] New GitHub organization
  - [x] Update all governance docs to reflect the name selected for the Foundation. (https://github.com/openjs-foundation/bootstrap/pull/126)
  - [x] Initial email lists - [#134](https://github.com/openjs-foundation/bootstrap/issues/134)
  - [x] Confirm list of initial Impact projects and land as PROJECTS.md
  - [x] Land Common Code of Conduct in OpenJS Foundation org - PR https://github.com/openjs-foundation/bootstrap/pull/147
  - [x] Target for Initial CPC meeting (collaborator summit) [#125](https://github.com/openjs-foundation/bootstrap/issues/125)
  - [x] Checklist for projects (refs to OpenJS Foundation, changes for moderation etc.) [#121](https://github.com/openjs-foundation/bootstrap/issues/121)
  - [x] Work with projects to identify initial CPC representatives (deadline May 1?) [#152](https://github.com/openjs-foundation/bootstrap/issues/152)
  - [x] Create admin repo and land initial governance docs there [155] (https://github.com/openjs-foundation/bootstrap/issues/155) (Task done, deemed unnecessary, renaming the bootstrap repo to CPC and landing docs there)

* Post-bootstrap
  - [x]  Ask projects to start updating references to docs in admin repo (ex coc etc.)
  - [x] New Zoom, Youtube etc.
  - [ ] Document/define initial process for handling reports to report@openjsf.org (Manil has volunteered to make a first draft)
  - [ ] Review Foundation infrastructure and rethink how we manage it.
  - [ ] Move/update JSF cla-bot (see #124)
  - [ ] Project Directed Funding (https://github.com/nodejs/bootstrap/issues/90) 
  - [ ] Complete language for project exit clause (https://github.com/nodejs/bootstrap/issues/96)
  - [x] draft initial process for electing voting members from the non-impact projects.  Nick/Michael to 
  - [x] Add entry point for projects wanting to join on README.md and review project progression (Jory will help with this one)
  work on that together.

**Comment by MylesBorins** [comment]
Attempted to document this in a board

--> https://github.com/openjs-foundation/bootstrap/projects/2

LMK if this should be close or if it makes sense to keep both

**Comment by mhdawson** [comment]
I'm ok with using the board, but I think we might want to keep an open issue that points to the board so that we get an issue added to the agenda as a reminder that we should go through it.

**Comment by MylesBorins** [comment]
@mhdawson lets just keep this issue open then

**Comment by obensource** [comment]
@mhdawson updated your admin repo task definition to reflect priority changes. 👍

**Comment by obensource** [comment]
@mhdawson also this is as good a place as any to ask: I'm not sure how acceptable it is to edit another member's issue definition (as a matter of principal) – it just seemed easier in this case to update it to reflect current changes. Lmk if that's not ok. Thanks Michael! 👍

**Comment by mhdawson** [comment]
Updating is good with me :) Thanks for keeping it up to date.

**Comment by MylesBorins** [comment]
The CPC is officially boostraped !!!

Renaming issue to keep it for tracking

**Comment by obensource** [comment]
@MylesBorins WAHOO! So amazing to see this come together! Fantastic work everyone! 👏👏👏

![computerclub](https://user-images.githubusercontent.com/1910457/57784894-8e63bc00-76e5-11e9-8f0f-faa19b8ee074.gif)

**Comment by joesepi** [comment]
There were only two remaining issues that are actively being worked on ([#185] & [#90]) and one languishing issue ([#96]) that I've added the cpc-agenda label to and we can track them individually. Here's to closing out the Post-Bootstrap work issue 🎉
