### ISSUE TITLE
[ONBOARDING] AMP

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#1546]
## Project Onboarding Checklist - AMP

**Intended Stage: Growth**

- [x] Adopt the OpenJS Foundation Code of Conduct _(tracked in https://github.com/ampproject/wg-codeofconduct/issues/6)_
- [x] Update project CoC reporting methods to include OpenJS Foundation escalation path _(tracked in https://github.com/ampproject/wg-codeofconduct/issues/6)_
- [x] List official domains, indicating which one(s) the project commits to transfer to the OpenJS Foundation following graduation _(tracked in https://github.com/ampproject/wg-foundation-onboarding/issues/3)_
- [x] Identify and document other core project infrastructure _(tracked in https://github.com/ampproject/wg-infra/issues/18 and https://github.com/ampproject/wg-infra/issues/19)_
- [x] If choosing to use a Contributor License Agreement (CLA) or Developer Certificate of Origin (DCO), make selection and implement appropriate tool _(tracked in https://github.com/ampproject/meta-tsc/issues/25)_
- [x] Add or Update Governance.md document (required for Impact stage) _(tracked in https://github.com/ampproject/meta/issues/46)_
- [x] Confirm required files in place (CODE_OF_CONDUCT.md, LICENSE.md) _(tracked in https://github.com/ampproject/wg-foundation-onboarding/issues/7 and https://github.com/ampproject/wg-codeofconduct/issues/6)_
- [x] [Project Charter](https://github.com/openjs-foundation/cross-project-council/blob/master/PROJECT_CHARTER_TEMPLATE.md) is published on website or github _(tracked in https://github.com/ampproject/meta/issues/45)_
- [x] Update legal copyright notice on project website and github _(tracked in https://github.com/ampproject/wg-foundation-onboarding/issues/12)_
- [x] Add OpenJS Foundation logo to project website _(tracked in https://github.com/ampproject/wg-outreach/issues/60)_
- [x] Add Project logo to OpenJS Foundation website; update PROJECTS.md file
- [x] List relevant trademarks, indicating which one(s) the project commits to transfer to the OpenJS Foundation following graduation _(tracked in https://github.com/ampproject/wg-foundation-onboarding/issues/17)_
- [x] If project is using crowdfunding platforms, add disclaimer to platforms _(tracked in https://github.com/ampproject/wg-foundation-onboarding/issues/10)_
- [x] Identify individuals from the project to join the CPC _(tracked in https://github.com/ampproject/wg-foundation-onboarding/issues/11)_
- [x] Document project and foundation contacts for:
  * marketing & social media
  * infrastructure
  * legal/governance help
  _(tracked in  https://github.com/ampproject/wg-foundation-onboarding/issues/4)_
