### ISSUE TITLE
Updates to requirements of potential new Regular Members

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#513]
There has been some discussion about the requirements for new Regular Members asking to join the Cross Project Council. Part of why this is being discussed is that Regular and Voting Members are privy to private discussions and confidentiality is expected.

Below are proposed changes that I've culled from various discussions. We can discuss them further here to get some consensus and then I can create a pull request updating documents listed below.

I've numbered the bullets below for people to use as references in the discussion.

#### Proposed requirements: (one of the following is required)
1. An active member of a project community or collaboration space which is defined as having recent, sustained contributions to the project during the past 90 days
2. A demonstrated level of contribution to the CPC's work (meetings, issues, pull-requests) as an observer during the past 30 days

#### Means for approval/rejection, if citing project affiliation: (one of the following is required)
1. Project representatives, for the project the user is claiming affiliation with, should have the ability to approve/reject that project for being considered for that user
2. the CPC rep for impact projects and the elected rep for non-impact projects to have to approve/reject the nomination.

#### Files needing updates:
- [Charter](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#regular-members)
- [Governance](https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#approving-and-onboarding-regular-members)
- [README](https://github.com/openjs-foundation/cross-project-council#regular-members)

#### Todo:
- [x] collect criteria from discussions
- [x] propose and discuss new requirements (in this issue)
- [x] create a pull request for discussed updates in appropriate places
- [x] create a PR template for regular members with guidance and requirements

**Comment by mcollina** [comment]
I'm +1 with the change.

**Comment by mhdawson** [comment]
I'm wondering if 30 days for CPC involvement would be enough?

**Comment by joesepi** [comment]
@mhdawson 90 days would align with other requirements. I only said 30 because we meet weekly and are fairly active. I'm open to upping that requirement though.

**Comment by mcollina** [comment]
I'm ok with saying 30 days.

**Comment by joesepi** [comment]
This is adequately captured in the associated pull request #531
